# Generated by Django 5.1.7 on 2025-03-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='base_path',
            field=models.CharField(blank=True, help_text='Custom base path for module URLs (empty to use module_id)', max_length=100),
        ),
    ]
